name: Add Issues and PRs to GitHub Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to GitHub Project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const projectNumber = 3; // Tu número de Project
            const user = "St4rVul";

            const { data: projects } = await github.graphql(`
              query($user: String!) {
                user(login: $user) {
                  projectsV2(first: 100) {
                    nodes {
                      id
                      title
                      number
                    }
                  }
                }
              }
            `, { user });

            const project = projects.user.projectsV2.nodes.find(p => p.number === projectNumber);
            if (!project) {
              throw new Error("No se encontró el proyecto número " + projectNumber);
            }

            const contentId = context.payload.issue?.node_id || context.payload.pull_request?.node_id;

            if (!contentId) {
              throw new Error("No se encontró el node_id del issue o pull request.");
            }

            await github.graphql(`
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {
                  projectId: $projectId,
                  contentId: $contentId
                }) {
                  item {
                    id
                  }
                }
              }
            `, {
              projectId: project.id,
              contentId
            });

            console.log("✅ Item agregado correctamente al Project");
